// src/components/Footer.tsx
import Git from '/assets/img/git.svg';
import Linkedin from '/assets/img/linkedin.svg';

const Footer = () => {
  return (
    <>

      <div className='w-auto h-auto mt-20 bg-purple text-white'>

        <div className="h-auto w-auto flex justify-center items-center px-[5rem] py-5 border-b">
          <div className='justify-start flex items-start text-center w-1/2  h-auto'>
            Connect with me on social media:
          </div>
          <div className='flex justify-end w-1/2 h-auto gap-4'>
            <div className="h-10 w-10 bg-white justify-center flex items-center rounded-full shadow-custom cursor-pointer">

              <a href="https://github.com/luanoliveiradasilva" target="_blank" className='cursor-pointer'>
                <img className='h-7 w-7' src={Git} alt="Git" />
              </a>


            </div>

            <div className="h-10 w-10 bg-white justify-center flex items-center rounded-full shadow-custom cursor-pointer">
              <a href="https://www.linkedin.com/in/luan-nascimento-oliveira/" target="_blank" className='cursor-pointer'>
                <img className='h-5 w-5' src={Linkedin} alt="Linkedin" />
              </a>
            </div>
          </div>
        </div>
        <div className='grid grid-cols-3 gap-4 p-9 '>
          <div className='text-center justify-center items-center'>
            LUAN NASCIMENTO OLIVEIRA
            <p> A growing Developer.</p>
          </div>

          <div className='text-center justify-center items-center'>
            USEFUL LINKS
            <p>Home</p>
            <p>About</p>
            <p>Skills</p>
            <p>Projects</p>
          </div>

          <div className='text-center justify-center items-center'>
            CONTACT
            <p>luanoliveira1107@gmail.com</p>
            <p>+351 910882158</p>
          </div>

        </div>

        <div className='text-center justify-center items-center p-4 bg-purple-black '>
          © 2024 Copyright: Designed and built by Luan Nascimento Oliveira
        </div>

      </div>

    </>
  );
};

export default Footer;

// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { ViewportScroller } from '@angular/common';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

  private viewPortScroller: ViewportScroller;

  constructor(viewPortScroller: ViewportScroller) {
    this.viewPortScroller = viewPortScroller;
  }
  
  scrollPageWithMenu(elementId: string): void {
    this.viewPortScroller.scrollToAnchor(elementId);
  }
}

<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a class="mediaSocial" href="https://www.linkedin.com/in/luan-nascimento-oliveira/" target="_blank">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-linkedin"
          viewBox="0 0 16 16">
          <path
            d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
        </svg>
      </a>
      <a class="mediaSocial" href="https://github.com/luanoliveiradasilva" target="_blank">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-github"
          viewBox="0 0 16 16">
          <path
            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
        </svg>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Luan Nascimento Oliveira
          </h6>
          <p>
            A growing Developer.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <ul class="navbar-nav flex-grow">
            <p>
              <li (click)="scrollPageWithMenu('home')" class="nav-item" [routerLinkActive]="['link-active']"
                [routerLinkActiveOptions]="{ exact: true }">
                <a class="nav-link text-dark" [routerLink]="['.']">Home</a>
              </li>
            </p>
            <p>
              <li (click)="scrollPageWithMenu('about')" class="nav-item" [routerLinkActive]="['link-active']">
                <a class="nav-link text-dark" [routerLink]="['.']">About</a>
              </li>
            </p>
            <p>
              <li (click)="scrollPageWithMenu('tech-stack')" class="nav-item" [routerLinkActive]="['link-active']">
                <a class="nav-link text-dark" [routerLink]="['.']">Tech Stack</a>
              </li>
            </p>
            <p>
              <li (click)="scrollPageWithMenu('project')" class="nav-item" [routerLinkActive]="['link-active']">
                <a class="nav-link text-dark" [routerLink]="['.']">Projects</a>
              </li>
            </p>
          </ul>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p>
            <i class="fas fa-envelope me-3"></i>
            luanoliveira1107@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +351 910882158</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Designed and built by Luan Nascimento Oliveira </a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
